AllCops:
  Include:
    - Gemfile
    - Rakefile
    - bin/*
    - ebook_renamer.gemspec
    - lib/**/*.rb
    - test/**/*.rb
# Avoid long parameter lists
ParameterLists:
  Max: 5
  CountKeywordArgs: true

MethodLength:
  CountComments: false
  Max: 15

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 4

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

AccessModifierIndentation:
  Enabled: false

# Limit line length
LineLength:
  Enabled: false

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Enforce Ruby 1.8-compatible hash syntax
HashSyntax:
  Enabled: true

# No spaces inside hash literals
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Allow dots at the end of lines
DotPosition:
  Enabled: false

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false

EmptyLinesAroundAccessModifier:
  Enabled: true

# Align ends correctly
EndAlignment:
  AlignWith: variable

# Indentation of when/else
CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: false

DoubleNegation:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

StringLiterals:
  EnforcedStyle: double_quotes
