require 'thor'
require 'code_lister'
require 'agile_utils'
require_relative 'ebook_renamer/core_ext/hash'
require_relative 'ebook_renamer/version'
require_relative 'ebook_renamer/logger'
require_relative 'ebook_renamer/helper'
require_relative 'ebook_renamer/cli'
